# Generated by Django 5.0 on 2024-01-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_heart_dilikes_generaldata_heart_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldata',
            name='heart_Dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='heart_Likes',
            field=models.IntegerField(default=0),
        ),
    ]
